# Configuration du fichier Vagrant en utilisant la version 2 du format de configuration
Vagrant.configure(2) do |config|

  # Définition d'une machine virtuelle nommée "ansible"
  config.vm.define "ansible" do |ansible|
    
    # spécifie l'image de base à utiliser pour la VM

    #Utiliser l'image "net9/ubuntu-24.04-arm64"  pour les mac m1,4 (arm)

    ansible.vm.box = "ubuntu/bionic64"
    
    #Attribue le nom d'hôte "ansible" à la machine virtuelle
    ansible.vm.hostname = "ansible"

    # Reférencie install_ansible.sh pour installer et configurer les composants de cette VM
    ansible.vm.provision "shell", path: "install_ansible.sh"
    
    # Configure un réseau privé avec une adresse IP fixe pour cette machine virtuelle
    ansible.vm.network "private_network", ip: "192.168.10.10"
    
    # Spécifie la configuration du fournisseur, ici "VirtualBox"
    ansible.vm.provider "virtualbox" do |v|
      
      # Nomme la machine virtuelle "ansible" dans VirtualBox
      v.name = "ansible"
      
      # Alloue 1024 Mo de mémoire vive à la machine virtuelle
      v.memory = 1024
      
      # Alloue 1 CPU à la machine virtuelle
      v.cpus = 1
    end
  end

  # Définition d'une machine virtuelle nommée "target_ansible"
  config.vm.define "target" do |target|
    
    # spécifie l'image de base à utiliser pour la VM
    target.vm.box = "ubuntu/bionic64"

    #Attribue le nom d'hôte "target" à la machine virtuelle
    target.vm.hostname = "target"

    # Reférencie configure_servers_target.sh pour installer et configurer les composants de cette VM
    target.vm.provision "shell", path: "configure_servers_target.sh"

    # Configure un réseau privé avec une adresse IP fixe pour cette machine virtuelle
    target.vm.network "private_network", ip: "192.168.10.20"

    # Spécifie la configuration du fournisseur, ici "VirtualBox"
    target.vm.provider "virtualbox" do |v|

      # Nomme la machine virtuelle "target" dans VirtualBox
      v.name = "target"

      # Alloue 1024 Mo de mémoire vive à la machine virtuelle
      v.memory = 1024

      # Alloue 1 CPU à la machine virtuelle
      v.cpus = 1
    end
  end

end
