global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']

  - job_name: 'Jenkins'
    metrics_path: /prometheus
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['jenkins:8080']
    basic_auth:
      username: 'admin'
      password: 'passer123'

  - job_name: 'sonarqube'
    metrics_path: /api/prometheus/metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['sonarqube:9000']
    basic_auth:
      username: 'admin'
      password: 'LeCloudFacile123@#'

  - job_name: 'proxy'
    static_configs:
      - targets: ['proxy:80']

