# Base officielle Jenkins inbound agent avec JDK 21
FROM jenkins/inbound-agent:latest-jdk21

USER root

#  Installer Docker CLI, Git, Curl, etc.
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip \
    git \
    curl \
    docker.io \
    unzip \
    jq \
    ca-certificates \
    lsb-release \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

#  Installer les outils Python
RUN pip3 install --no-cache-dir --upgrade pip --break-system-packages && \
    pip3 install --break-system-packages pytest coverage

#  Installer Trivy (scanner de vulnérabilités)
ENV TRIVY_VERSION=0.50.0
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${TRIVY_VERSION}

#  Revenir à l'utilisateur Jenkins pour les jobs
USER jenkins

# Dossier de travail par défaut
WORKDIR /home/jenkins
